### ISSUE TITLE
Print attribute list of components in Python

### ISSUE THREAD

**Issue by m-mirz** [sogno-platform/dpsim#10]
It would be convenient to able to print the complete lists of attributes of each component from the Python interface including each attribute's type, e.g. real or complex.

**Comment by JTS22** [comment]
This functionality has been implemented in 6806cc3da8035728230a551d4075850b4b5388ea and f4dcd1b14acf6de7289769cdaa52a6903c54516c, which got merged in ff0350020bfdea3144444da4e9ab7076ac6ffe23. A list of attributes can be printed with the `print_attribute_list`-function on any identified object or by just calling `print` on that object. For details about an attribute, use `print_attribute(attribute_name)`. An example for how to use these functions is given [this notebook](https://github.com/sogno-platform/dpsim/blob/master/Examples/Notebooks/Circuits/CS_R2CL%20print_attributes.ipynb).
