### ISSUE TITLE
lock-free queue for interface to villas etc.

### ISSUE THREAD

**Issue by m-mirz** [sogno-platform/dpsim#111]
Could be based on this implementation:
https://moodycamel.com/blog/2013/a-fast-lock-free-queue-for-c++.htm

Requirements:
- provide lock-free communication between two threads in dpsim, independent of communication interface implementation
- C++ not C

**Comment by JTS22** [comment]
This is being worked on on branch [lock-free-queue](https://github.com/sogno-platform/dpsim/tree/lock-free-queue)
