### ISSUE TITLE
Minor bug report

### ISSUE THREAD

**Issue by junjie-zh** [sogno-platform/dpsim#118]
https://github.com/sogno-platform/dpsim/blob/cfb4e2cf63ded5384169dc1d09e7604a98a6e785/dpsim-models/src/DP/DP_Ph1_RXLoad.cpp#L122

Here `&**mSubInductor->mRightVector` should be changed to `&**mSubCapacitor->mRightVector`.

**Comment by m-mirz** [comment]
@junjie-zh thanks for catching that! Fixing this in #136 
@dinkelbachjan FYI

**Comment by m-mirz** [comment]
Closed with #136
