### ISSUE TITLE
Automated pypi package deployment

### ISSUE THREAD

**Issue by dinkelbachjan** [sogno-platform/dpsim#127]

**Comment by dinkelbachjan** [comment]
@m-mirz We would like to consider start with the automated pypi package deployment. Was this manually done so far? Or is there any starting point already somewhere?

**Comment by JTS22** [comment]
The deployment can probably be implemented using GitHub actions as described in https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/ . The `python -m  build --sdist --wheel --outdir dist/` command already works for dpsim. Given that the generated package has the correct format for PyPi, the upload should be quite easy to implement.

**Comment by dinkelbachjan** [comment]
@m-mirz Procedure for new DPsim version:
    - Create a new tag with increased version number
    - Update setup.cfg
    - Update CMakeLists.txt
    - Update Dockerfile
A new pypi package will be then deployed accordingly.
