### ISSUE TITLE
System Matrix Stamp of DP_Ph3_VoltageSource

### ISSUE THREAD

**Issue by cwirtz-fgh** [sogno-platform/dpsim#130]
### **System Matrix Stamp of DP_Ph3_VoltageSource**
In DP_Ph3_VoltageSource Line 69 the stamp for phase C differs from A and B:

`if (terminalNotGrounded(0)) {
...

		Math::addToMatrixElement(systemMatrix, matrixNodeIndex(0, 1), mVirtualNodes[0]->matrixNodeIndex(PhaseType::B), Complex(-1, 0));
		Math::addToMatrixElement(systemMatrix, mVirtualNodes[0]->matrixNodeIndex(PhaseType::B), matrixNodeIndex(0, 1), Complex(-1, 0));

		Math::addToMatrixElement(systemMatrix, matrixNodeIndex(0, 2), mVirtualNodes[0]->matrixNodeIndex(PhaseType::C), Complex(-1, 0));
		Math::addToMatrixElement(systemMatrix, mVirtualNodes[0]->matrixNodeIndex(PhaseType::C), matrixNodeIndex(0, 2), -Complex(-1, 0));
	}`

This leads to phase C beeing shifted when transformed into EMT frame and unintended model behaviour:
Bug ( with -Complex(-1,0)); )
![grafik](https://user-images.githubusercontent.com/67785000/200838778-43a4b553-65d4-4a18-a1bd-d995def31a4d.png)

Fixed (with Complex(-1,0)); )
![grafik](https://user-images.githubusercontent.com/67785000/200838073-e02903df-94a5-40dc-99ee-ba2287d629ee.png)

**Comment by m-mirz** [comment]
Fixed in #137
To be reviewed by @dinkelbachjan

**Comment by m-mirz** [comment]
Closed by #137
