### ISSUE TITLE
Check, improve and document subcomponent handling

### ISSUE THREAD

**Issue by dinkelbachjan** [sogno-platform/dpsim#131]
- [x] Check that explicit subcomponent tasks are only defined when reasonable in terms of expected computational effort, otherwise let the subcomponent's pre- and poststep routines be handled by the supercomponent
- [x] Every `SimPowerComp` has a vector `mSubComponents` of subcomponents but most classes derived from `SimPowerComp` have their subcomponents as separate member variables, not utilizing this list. 
  - Make use of `mSubComponents` to harmonize calling pre- and poststep routines, as for example shown [here](https://github.com/sogno-platform/dpsim/blob/a4c9b5cfc3f40eb0eb80d555d9562455e1f489d0/dpsim-models/src/DP/DP_Ph1_AvVoltageSourceInverterDQ.cpp#L347-L352) 
- [x] Document the different concepts of how to handle pre- and poststep routines of subcomponents

**Comment by JTS22** [comment]
Classes which include subcomponents:
| Class | Uses `mSubComponents` | Pre- and Post-step called by parent? |
|--------------|-----------|------------|
|DP_Ph1_VoltageSourceInverterDQ|yes|yes|
|DP_Ph1_NetworkInjection|yes|yes|
|DP_Ph1_PiLine|no|yes|
|DP_Ph1_PQLoadCS|no|no|
|DP_Ph1_RxLine|no|no|
||||

**Comment by JTS22** [comment]
In addition to the changes made in #141, I propose another way to further unify the behavior of components with subcomponents: By creating a shared superclass MNASimPowerComp that is derived from both SimPowerComp and MNAInterface, it becomes possible to extract the various MNA method calls on the subcomponents into this common superclass. This means that the parent components only register their subcomponents once (e. g. through `addMNASubComponent`) and then only contain methods concerned with the MNA operations in the parent. The calls to the MNA methods of the child are handled by the superclass instead, drastically cutting down on the amount of duplicated code (especially the `for (auto comp : mSubComponents)` loop) in the parent classes. The `MNAPreStep` and `MNAPostStep` classes contained in almost all parent components can also be merged into the common superclass. A first working example of this can be found in https://github.com/sogno-platform/dpsim/tree/unify-mna-subcomponents (Comparison with #141 in https://github.com/sogno-platform/dpsim/compare/subcomponents...unify-mna-subcomponents).

**Comment by dinkelbachjan** [comment]
@m-mirz We are thinking of inserting a new class `CompositePowerComp` as described above to unify the subcomponent handling. What do you think about that?
