### ISSUE TITLE
Documentation attribute system

### ISSUE THREAD

**Issue by dinkelbachjan** [sogno-platform/dpsim#133]
@m-mirz 

- [x] Getting started by sketching content

**Comment by m-mirz** [comment]
Hugo does not require themes as submodules anymore. You can now include them as go modules: https://gohugo.io/hugo-modules/
Besides, Github added support for latex in markdown files. So you can directly view the equations even without a static website generator :-)

I would be open to move the entire dpsim docs into the dpsim code repo. What do you think? @dinkelbachjan @JTS22

**Comment by JTS22** [comment]
I do not know exactly how the docs are currently hosted, but including them in the dpsim code repo makes sense to me. This would allow to find and read them directly on GitHub and to transparently update them with every (code) pull request.

**Comment by dinkelbachjan** [comment]
Yes, I would also prefer that, hoping that this also reduces the barrier to contribute to them
