### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by stv0g** [sogno-platform/dpsim#167]
There is a broken link in the docs on the following page:

https://sogno.energy/dpsim-docs/docs/getting-started/build/#cmake-for-linux

linking to the [fedora installation script](https://git.rwth-aachen.de/acs/public/simulation/dpsim/dpsim/-/blob/master/Packaging/install-fedora-deps.sh)

**Comment by georgii-tishenin** [comment]
hey @stv0g, looks like @leonardocarreras  fixed it in the commit https://github.com/sogno-platform/dpsim/commit/9eee33a70849f609f5b1aea39d1290e27e775705.
Shall we close this issue?
