### ISSUE TITLE
Figures in the documentation are broken

### ISSUE THREAD

**Issue by cuihantao** [sogno-platform/dpsim#203]
**Describe the bug**

Figures do not load properly in documentation. 

**To Reproduce**
1. Go to https://dpsim.fein-aachen.org/docs/overview/architecture/
You will see the missing figures.

**Expected behavior**
Figures to load properly.

**Screenshots**
Not needed.

**Comment by stv0g** [comment]
I think this PR might fix the issue https://github.com/sogno-platform/dpsim/pull/165

@m-mirz @dinkelbachjan Can we merge it?

**Comment by m-mirz** [comment]
finally #165 is merged :-)
