### ISSUE TITLE
Documentation is not rendering properly.

### ISSUE THREAD

**Issue by rahulbhadani** [sogno-platform/dpsim#211]
Hi,
  Thanks for creating an open-source `dpsim` project. I found out that documentation's latex code at https://dpsim.fein-aachen.org/docs/concepts/powerflow/ are not being rendered properly.

Further, an image at https://dpsim.fein-aachen.org/docs/models/transformer/ seems to be missing.

Similar issues at https://dpsim.fein-aachen.org/docs/models/rlc-elements/, https://dpsim.fein-aachen.org/docs/models/rlc-elements/

Can you please fix them?

Thank you.
Rahul

**Comment by m-mirz** [comment]
fixed in #165
