### ISSUE TITLE
Make dpsim compile with clang 14 and GCC 12

### ISSUE THREAD

**Issue by JTS22** [sogno-platform/dpsim#227]
The compilation with GCC12 seems to be fixed on the newest master commit https://github.com/sogno-platform/dpsim/commit/b51142411e63a9b1f6a29f150de3d7e066209203. The CI still seems to use GCC11 though (see https://github.com/sogno-platform/dpsim/actions/runs/5454599508/jobs/9924938203). Compilation with clang (v. 14.0.5) still does not work though, even when not treating warnings as errors.

**Comment by n-eiling** [comment]
clang compilation is fixed by #293
