### ISSUE TITLE
VILLASnode Examples do not run in current Dev container

### ISSUE THREAD

**Issue by JTS22** [sogno-platform/dpsim#231]
When using the dev-container from the current `Dockerfile.dev`, none of the VILLASnode-Examples can be executed, because they require the presence of the `libxil` shared library (https://github.com/VILLASframework/libxil). Because the last push of the dev image to Docker hub happened over 6 months ago, the pipeline still uses an outdated image, in which this dependency was apparently not present. Therefore, the VILLASnode-Examples still work in the GitHub-Pipeline, but not locally.
Options to resolve this are:
1. Compile VILLASnode with the `WITH_FPGA=OFF` option to disable the dependency (as in #232 )
2. Somehow install the dependency manually in the dpsim-Dockerfile
3. Update the VILLASnode version used in the DPsim-containers (see #233), as the issue has been fixed there (https://github.com/VILLASframework/node/pull/694)

**Comment by dinkelbachjan** [comment]
We target to implement the third option.

**Comment by dinkelbachjan** [comment]
The VILLASnode version and, correspondingly, the Docker hub dev image have been updated with the merge of PR #245
