### ISSUE TITLE
Update VILLASnode version

### ISSUE THREAD

**Issue by JTS22** [sogno-platform/dpsim#233]
The version of VILLASnode used in the current Dockerfiles is over 6 months old. It should probably be updated at some point.

Related to #231

**Comment by stv0g** [comment]
@JTS22 Please take note that the correct spelling is "VILLASnode", not "Villas Node" or "VILLASNode" or "VILLAS node" :)

**Comment by JTS22** [comment]
@stv0g Thanks for the reminder, I updated the spelling in all relevant issues / PRs :)
