### ISSUE TITLE
Compilation warnings and some code improvements

### ISSUE THREAD

**Issue by leonardocarreras** [sogno-platform/dpsim#256]
**Description of the bug**
During compilation in a new environment, errors related to `"-Woverloaded-virtual"` problems with the compiler arise in various files related to SynchronGenerator* classes and the missing argument `Int timeStepCount` in the `DIakopticsSolver` logger

**To Reproduce**
1. Install a new environment
2. Install dependencies
3. Compile with `cmake --build . -j4 --target dpsimpy`

**Expected behavior**
Build successful

**Desktop (please complete the following information):**
 - OS: Fedora 38

**Additional context**
This warning could also be ignored with pragma instructions, but we actually want to override it, as reading the intention in the code.

The warning is of type:
`warning: 'DerivedClass::function' hides overloaded virtual function [-Woverloaded-virtual]`

**Comment by n-eiling** [comment]
fixed by #293
