### ISSUE TITLE
Duplicate file?

### ISSUE THREAD

**Issue by stv0g** [sogno-platform/dpsim#26]
Are these files duplicates?

- https://github.com/sogno-platform/dpsim/blob/master/Source/pybind/dpsim-villas.cpp
- https://github.com/sogno-platform/dpsim-villas/blob/main/src/pybind-dpsim-villas.cpp

Apparently, only the latter is used.

@JTS22 
@m-mirz

**Comment by JTS22** [comment]
Yes, as far as I know, these are duplicates. The former is obsolete and is removed in PR #22 .

**Comment by m-mirz** [comment]
I confirm.
