### ISSUE TITLE
Fix Doxygen documentation

### ISSUE THREAD

**Issue by dinkelbachjan** [sogno-platform/dpsim#260]
The doxygen documentation is broken:
https://sogno.energy/dpsim/doxygen/index.html

**Comment by leonardocarreras** [comment]
![image](https://github.com/sogno-platform/dpsim/assets/88666277/801c608b-48ff-47f8-8214-0feefb14eaf4)

In local is working correctly.

_Related but not part of this problem:_ the actions worker is using `-j$(nproc) ` as argument in the compilation... Should this be corrected in a new issue? 
https://github.com/sogno-platform/dpsim/blob/d2cfcda8b38e383a73af5c402c7dc5b01ff15857/.github/workflows/documentation.yaml#L24-L27
