### ISSUE TITLE
Fix VILLASnode in Dockerfiles

### ISSUE THREAD

**Issue by pipeacosta** [sogno-platform/dpsim#291]
After some changes in VILLASnode's structure, mainly related to the removal of VILLAScommon and VILLASfpga as submodules, building the DPsim's docker image from Dockerfile.dev issues an error. The issue will be solved by changing the `VILLAS_VERSION` variable to a more up-to-date commit of VILLASnode.

**Comment by leonardocarreras** [comment]
I think part of your solution is [here](https://github.com/sogno-platform/dpsim/compare/master...fix-devcontainer)

**Comment by leonardocarreras** [comment]
Closed #291 via #292
