### ISSUE TITLE
A typo in dpsim_classes_simulation.svg

### ISSUE THREAD

**Issue by georgii-tishenin** [sogno-platform/dpsim#308]
`ODESolver` class is twice in the [dpsim_classes_simulation.svg](https://github.com/sogno-platform/dpsim/blob/master/docs/hugo/content/en/docs/Overview/Architecture/dpsim_classes_simulation.svg), used in [Architecture | DPsim](https://dpsim.fein-aachen.org/docs/overview/architecture/).

From the context it should be `ODESolver` and `DAESolver`. Shall I fix that?

**Comment by stv0g** [comment]
That would be great :) Is there maybe another new solver class which we could add instead?

**Comment by georgii-tishenin** [comment]
Good point. I was actually going to just replace one of `ODESolvers` by `DAESolver` in the figure. I assume this was a typo from the start.

Though inheritance diagram in [Solver class reference](https://sogno.energy/dpsim/doxygen/class_d_psim_1_1_solver.html) has more classes on the same level. The additional ones are `DiakopticsSolver`,   `ODEIntSolver` and `PFSolver`.
