### ISSUE TITLE
How to add/remove faults.

### ISSUE THREAD

**Issue by Faisal-700** [sogno-platform/dpsim#317]
Hello,

Right now I have just started exploring the repository. Does DPsim support adding/remove fault for line and bus. Also does it support Trip of generator or any other instrument. If it support then please guide or example for it.

**Comment by leonardocarreras** [comment]
Hi @Faisal-700, sorry for the reply delay

You may want to explore the faults in the examples, i.e. 
https://github.com/sogno-platform/dpsim/blob/ad81d7e8af1328a648ab58279e0962f6f1ff1b15/dpsim/examples/cxx/Circuits/DP_SynGenTrStab_SMIB_Fault.cpp#L22

**Comment by leonardocarreras** [comment]
Closing as there is no new feedback
