### ISSUE TITLE
Workflow error due to 2FA missing (PyPA)

### ISSUE THREAD

**Issue by leonardocarreras** [sogno-platform/dpsim#320]
From the log:

>  ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/          
>          User 'jdinkelbach' does not have two-factor authentication enabled.    
>          Please enable two-factor authentication before attempting to upload to 
>          PyPI. See https://test.pypi.org/help/#two-factor-authentication for    
>          more information.   

Would it be good to think about changing the user to a separate one for the package uploads of DPSim? What is your opinion @m-mirz @stv0g @dinkelbachjan ?

**Comment by m-mirz** [comment]
I have overwritten Jan's token with mine. 2FA is enabled for my account. I hope it works now.
