### ISSUE TITLE
GitLab CI should not use a hard coded limit of 32 CPU cores

### ISSUE THREAD

**Issue by stv0g** [sogno-platform/dpsim#44]
Because it causes the buildbot to OOM kill arbitrary processes because of memory contraints:

Example: https://git.rwth-aachen.de/acs/public/simulation/dpsim/dpsim-github/-/jobs/1951371

**Comment by m-mirz** [comment]
This is not hardcoded anymore. Now nproc is used.

**Comment by stv0g** [comment]
Thanks :)
