### ISSUE TITLE
Docker-based installation instructions are out of date

### ISSUE THREAD

**Issue by stv0g** [sogno-platform/dpsim#52]
The DPsim documentation for a Docker-based setup refers to the `rwthacs/dpsim-dev` image which hasnt been updated for 7 months:

https://dpsim.fein-aachen.org/docs/getting-started/build/

I think it would also be much nicer if a user could start without building the image himself.
The current instructions seem far to complex.

**Comment by m-mirz** [comment]
I updated the image name. 

In the instructions it says... Alternatively, the image can be pulled from DockerHub like so...
Maybe I can highlight the sentence or mention this option first.

**Comment by stv0g** [comment]
Thanks :)
