### ISSUE TITLE
Add new SMIB system to Examples.h

### ISSUE THREAD

**Issue by dinkelbachjan** [sogno-platform/dpsim#69]
@martinmoraga We should add a common namespace in `Examples.h` for the newly introduced SMIB examples of #64 in order to ensure that all examples have a consistent parametrisation.

This could look like
```
namespace Examples {
namespace Grids {
namespace SMIBType2 {
  struct Line {
    ...
  }

  struct Fault {
    ...
  }
  
 ...
}
}
}
```

**Comment by martinmoraga** [comment]
@dinkelbachjan I think this issue is out-of-date or not?

**Comment by dinkelbachjan** [comment]
Yes, this has been done already
